[package]
name = "tree-sitter-janet-simple"
edition = "2024"
version = "0.0.8"
description = "Janet grammar for the tree-sitter parsing library"
license = "CC0-1.0"
readme = "README.md"
repository = "https://github.com/NTBBloodbath/tree-sitter-janet-simple"
build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]
autolib = false
autobins = false
autoexamples = false
autotests = false
autobenches = false

[lib]
name = "tree_sitter_janet_simple"
path = "bindings/rust/lib.rs"

[dependencies.tree-sitter-language]
version = "0.1"
[dev-dependencies.tree-sitter]
version = "0.25"
[build-dependencies.cc]
version = "1.0"
